### ISSUE TITLE
Game mode is not correctly detected

### ISSUE THREAD

**Issue by martinbonnin** [HearthSim/arcane_tracker#11]

**Comment by martinbonnin** [comment]
Same for rank

**Comment by martinbonnin** [comment]
Ideally, we should distinguish:

• ranked standard
• casual standard
• ranked wild
• casual wild
• arena
• tavern brawl

**Comment by martinbonnin** [comment]
As of now, Arena shoud be correctly detected, that's about it.

**Comment by barat** [comment]
So now we wait for ranked/casual and current rank in ranked :)

**Comment by Bastes** [comment]
Undetected indeed here too ^^ all my games are filed under trackobot as "ranked".

**Comment by martinbonnin** [comment]
This is available in the 2.30 beta. Click there to opt-in https://play.google.com/apps/testing/net.mbonnin.arcanetracker

**Comment by martinbonnin** [comment]
It's base on image recognition so not sure it works on 100% of devices screens/resolutions. If it fails for you, please upload a screenshot in the deck selection screen.
