### ISSUE TITLE
Don't display amount of card in deck when there's only one of it

### ISSUE THREAD

**Issue by slampisko** [HearthSim/arcane_tracker#16]
It works this way on HS Deck Tracker on Windows and it's much easier to see at a glance what card is in your deck once or twice.

Just to be clear, the behavior I'd like to see is:

Number of copies in deck | Behavior
--- | ---
0 | Card is grayed out, no number indicator
1 | Card is lit up, no number indicator
2+ | Card is lit up, number indicator
Legendary | Card is lit up, number indicator shows a star (this is currently the case)

Example: http://i.imgur.com/MHUzlDc.jpg

**Comment by martinbonnin** [comment]
Makes sense.

**Comment by martinbonnin** [comment]
fixed with 2.00
