### ISSUE TITLE
Overlay resizable

### ISSUE THREAD

**Issue by williamwebb** [HearthSim/arcane_tracker#22]
Allow deck overlay to be resizable & positionable. Option to have deck name/Record bottom deck aligned or bottom screen aligned.

**Comment by martinbonnin** [comment]
A resizable overlay is in the pipe, stay tuned ! 

Concerning the position, I'd really like to keep the overlay left align for now, making it positionable would complicate the code quite a lot and might add more confusion. Any use case that would require moving the overlay ?

Concerning, the alignment, I'm not sure what you mean. What's the difference between bottom deck or bottom screen ?

**Comment by williamwebb** [comment]
@martinbonnin When i say positionable i mean movable up/down in its current position, no change on the y axis. So say the deck only takes up 50% of the screen you could position it in the middle of the screen.

For Name/Record alignment I mean if the deck is say in the middle of the screen, it could either be attached to the deck in the middle, or aligned to the bottom of the screen.

For me at least the main part of this issue is the moving up/down of the deck list, the alignment of the name/record isn't important just a nice to have.
