### ISSUE TITLE
Choose language used in the app

### ISSUE THREAD

**Issue by mandaleFR** [HearthSim/arcane_tracker#38]
Hi,

As I am a french guy, my mobile is in french language BUT I play Hearthstone in english.

As you guess, the language used by the app is the default one set in the mobile. In my case, Arcane Tracker is in french even if Hearthstone is in english.

**Comment by martinbonnin** [comment]
Dammit, you're right, I thought Hearthstone would use the system language automatically. I'll add a language setting like the game has

**Comment by martinbonnin** [comment]
Right, thanks for noticing this :). 2.08 actually allows to chose the cards language. You still can't change the UI language (Android makes this very painful... :-(). But it should be ok for most use cases (hopefully)

**Comment by mandaleFR** [comment]
Hi Martin,

Yes for me, it's perfect as I know the name of the card in english but not in french.

The app can still be in french, it doesn't matter :)
