### ISSUE TITLE
Use image processing to detect rank/mode/format

### ISSUE THREAD

**Issue by martinbonnin** [HearthSim/arcane_tracker#41]

**Comment by ThaWeatherman** [comment]
Do they really not put ranks in the logs?

**Comment by sebastientromp** [comment]
They don't, unfortunately

**Comment by martinbonnin** [comment]
Yeaa, that would be too easy ;)

**Comment by ThaWeatherman** [comment]
They already have to know the ranks to match players, so why not just dump it to the log? Silly Blizzard. Maybe if enough of us complain they'll do it. It worked for fixing log location on mobile.

**Comment by sebastientromp** [comment]
There is quite a lot of info I'd like to see in the logs instead of having to rely on image recognition (current win/loss in Arena is another example). I tweeted once to Iksar or bbrode about this but never got any answer from them

**Comment by martinbonnin** [comment]
This is available in beta 2.30. Follow the link bellow to opt-in: 

https://play.google.com/apps/testing/net.mbonnin.arcanetracker

Also, this bug is a duplicate with https://github.com/HearthSim/arcane_tracker/issues/11. So I'm closing it and will follow up there.
