### ISSUE TITLE
app doesn't work anymore with current version of hearthstone

### ISSUE THREAD

**Issue by alexluchian** [HearthSim/arcane_tracker#49]
I know, it is because the lack of logging, but an issue about this should be open so people can discuss possible solutions

**Comment by Lachann** [comment]
Are the logs disabled completely or just not publicly readable? If so, could the tracker be made to work on a rooted phone?

**Comment by martinbonnin** [comment]
It is certainly technically doable to enable the app on rooted phones but it's a significant amount of work. Blizzard said they'll fix it: https://twitter.com/ywoo_dev/status/849730791303069701.
So I'd wait a bit and it should work again.

**Comment by OriginalAlienOne** [comment]
17 days since they said they'd fix it. Any word on this?

**Comment by williamwebb** [comment]
Yes/No. We have a working Root version, but a non Root version will require another update from Blizzard.

**Comment by martinbonnin** [comment]
It's working again :)
