### ISSUE TITLE
Raptor Hatchling and Direhorn Hatchling add "unknown" gift cards to the deck list when they die.

### ISSUE THREAD

**Issue by coversnail** [HearthSim/arcane_tracker#57]
When either of these two deathrattle cards die and shuffle their token cards into your deck they are displayed on the deck list as "unknown" gift cards, it would be great if the deck tracker displayed the token cards (Raptor Patriarch and Direhorn Matriarch) instead.

**Comment by martinbonnin** [comment]
Sounds reasonnable, I'll add it for next version.

**Comment by sebastientromp** [comment]
Just curious, how will you handle it? Will you have a list that you maintain yourself of all the token associations?

**Comment by martinbonnin** [comment]
Mostly yes. How it's handled today:

https://github.com/HearthSim/arcane_tracker/blob/master/app/src/main/java/net/mbonnin/arcanetracker/parser/PowerParser.java#L409.

That's a lot of manual work so maybe that can be factored in somewhere.

**Comment by martinbonnin** [comment]
Closing this one, it should be ok with 2.30
