### ISSUE TITLE
Tracker Not Passing Game Type to either Track-o-bot or HSReplay

### ISSUE THREAD

**Issue by notNDAface** [HearthSim/arcane_tracker#60]
The games are getting uploaded fine, but on track-o-bot, they are are labeled "Ranked" even if I'm playing a game with a friend. And on HSreply, it doesn't appear to be passing a game type at all. It's just blank.

**Comment by notNDAface** [comment]
Apologies. Looks like this issue has already been noted.

**Comment by martinbonnin** [comment]
Np, currently working on rank/mode detection. I'll hopefully release something in a few weeks
