### ISSUE TITLE
Game Mode and format aren't provided to HSReplay (and probably on track-o-bot)

### ISSUE THREAD

**Issue by Bastes** [HearthSim/arcane_tracker#62]
Hello,

Everything is in the title :) when I see the list of my games in HSReplay, I see neither game mode nor format columns filled, and in track-o-bot all games are apparently all "ranked" and "standard", even those that are actually casual or wild.

(also, awesome work, providing a tracker for mobile, I love it ^^d)

**Comment by martinbonnin** [comment]
duplicate with https://github.com/HearthSim/arcane_tracker/issues/41

**Comment by Bastes** [comment]
@martinbonnin sorry for the noise then ^^° I didn't think to check for a feature, thinking it was a bug.

**Comment by martinbonnin** [comment]
No problem at all, that's what the issues are for :)
