### ISSUE TITLE
Stored decks aren't recognised when using the new warlock hero (Nemsy)

### ISSUE THREAD

**Issue by coversnail** [HearthSim/arcane_tracker#64]
As I happened to be lucky and get the new hero today I have noticed an issue. When you start a game with your correct decklist selected Arcane Tracker always goes to a blank new decklist once the game starts, it will populate the cards correctly when drawn but is unaware of what is in your deck. You can manually reselect your correct decklist and this also functions correctly it just always defaults to a blank decklist when a game starts.

If you need any logs or information let me know as I imagine this skin will be reasonably rare for a while.

**Comment by martinbonnin** [comment]
ah, nice catch ! If you could go to settings => send feedback and send me the logfile, I'll fix this asap.

**Comment by martinbonnin** [comment]
This should be fixed with 2.30 available in beta right now.
