### ISSUE TITLE
Not tracking

### ISSUE THREAD

**Issue by tonyeds** [HearthSim/arcane_tracker#71]
I just downloaded arcane tracker, and after copying my deck string into the app and jumping into a game, it didn't actually track anything. All it was was a deck just on the left of my screen. I've never used a deck tracker before, so I very well could just be being an idiot, but I couldn't figure anything out! It it helps I'm using an elipsis 8 tablet. Please help me as I think the app is wonderful and would really enjoy using it

It would be worth mentioning as well that the opponens deck was not tracked either

**Comment by martinbonnin** [comment]
Hi ! Did you try to force close/restart Hearthstone ? This might be needed the very first time so that log configuration is updated.
