### ISSUE TITLE
not close window

### ISSUE THREAD

**Issue by persok** [HearthSim/arcane_tracker#73]
left mini window not close

https://youtu.be/EneJqIFcv6Y

fix it please
have a nice day

my phone is IM-A910S / Android 4.4.2

**Comment by martinbonnin** [comment]
You can close the overlay by clicking the gears icon and then 'quit'

**Comment by persok** [comment]
my problem is 'deck track overlay' not disapper

'my deck icon' (blue) click  => open 'deck track overlay' => retry blue icon click  => close  'deck track overlay' 

but my device

'my deck icon' (blue) click  => open 'deck track overlay' => retry blue icon click  => icon move left but not close 'deck track overlay'

it's always open...

**Comment by persok** [comment]
I think this issue only occurs in Android kitkat.
My another android phone(version 4.4.2) have same issue.
However, when I updated the 7.1.2 Custom ROM, this problem disappeared.  I hope it helps. Thanks you for your effort.

**Comment by martinbonnin** [comment]
Thanks for the details
