### ISSUE TITLE
2/3 Faldori Strider Spider Ambushes not recognised

### ISSUE THREAD

**Issue by BobTheMadCow** [HearthSim/arcane_tracker#80]
Been playing on Samsung Galaxy S7 Edge and when I shuffle spiders into my deck, I see 1 spider and 2 "unknown gift" cards in my deck.

Obviously I know what they are, so it's not a huge deal. Would be nicer if we just got a totalled number of the cards instead though (when they are half your deck it would be nice not to have to count them)

**Comment by martinbonnin** [comment]
should be good in 2.36
