### ISSUE TITLE
New cards not shown on HSReplay

### ISSUE THREAD

**Issue by mmascher** [HearthSim/arcane_tracker#82]
For some reason new cards are not shown, take for example this replay: https://hsreplay.net/replay/FZNQk2dXokfnJcjQpGrwND#turn=3b

The opponent played the basilisk which was a hidden card. Also, in my hand the scorpion is shown as LOOT_111 with the correct image but no text.

Replay uploaded with other tools (e.g.: HDT) are fine. This has been going on since Frozen Throne was released.

**Comment by martinbonnin** [comment]
Unless I miss something, Arcane Tracker cannot do much about this since the logs are uploaded 'as is'. Maybe the Android Logs are slightly different on Android ? 

Summon @jleclanche to see if he can see somethings from the Hsreplay.net side.

**Comment by martinbonnin** [comment]
Makes sense. That'll be fixed in next version.

**Comment by mmascher** [comment]
Fixed in 2.36
