### ISSUE TITLE
Arcane Tracker is uploading files with missing log lines

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/arcane_tracker#86]
I'm still finding files uploaded by net.mbonnin.arcanetracker/2.36 that are missing log lines.
The most likely culprit is timestamps on the exact second. Hearthstone (unity, to be precise) truncates timestamp to the second when the microseconds equal exactly zero, arcane tracker needs to be able to handle that.

**Comment by martinbonnin** [comment]
Any chance you can upload such a Power.log ? I'll add it to the unit tests.

**Comment by jleclanche** [comment]
I can't find one in my repos (I use a timestamp parsing library which doesn't have that issue in the first place). But maybe HSTracker or HDT have one seeing as they both had to fix that bug too.

**Comment by jleclanche** [comment]
Try something like `D 19:32:16 GameState.DebugPrintPower() ...`.

**Comment by martinbonnin** [comment]
Closing this one since we've seen only one instance so far. Feel free to reopen if it happens more frequently
